### ISSUE TITLE
KeyError: 'error' in TonCenterClient in case of an error "Ratelimit exceed"

### ISSUE THREAD

**Issue by QuisEgoSum** [yungwine/TonTools#20]
```
Traceback (most recent call last):
  File "<rootDir>/gdfgsdg.py", line 25, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "<rootDir>/gdfgsdg.py", line 19, in main
    print(await wallet.run_get_method('get_wallet_data', []))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quisegosum/Project/bets/toncoin/.venv/lib/python3.11/site-packages/TonTools/Contracts/Contract.py", line 151, in run_get_method
    return await self.provider.run_get_method(method=method, address=self.address, stack=stack)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quisegosum/Project/bets/toncoin/.venv/lib/python3.11/site-packages/TonTools/Providers/TonCenterClient.py", line 98, in run_get_method
    response = await process_response(response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/quisegosum/Project/bets/toncoin/.venv/lib/python3.11/site-packages/TonTools/Providers/TonCenterClient.py", line 34, in process_response
    raise TonCenterClientError(f'TonCenter failed with error: {response_dict["error"]}')
                                                               ~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'error'
```

Response from API:
```python
{'ok': False, 'result': 'Ratelimit exceed', 'code': 429}
```

**Comment by SerhiiL06** [comment]
A rate limit error means that you are making too many requests to the toncenter api. just increase the request interval (one second is enough) and everything will work.
